### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tazjin** [dell/thunderbolt-icm-dkms#1]
Hey guys,

what license is this  released under? I'm looking to make an Arch Linux package.

Cheers!

**Comment by tazjin** [comment]
There's a  GPLv2 header in some source files, can it be assumed that this applies to the whole thing?

**Comment by superm1** [comment]
Yes, GPLv2 for the whole thing.  I'll add a COPYING file later to indicate this.

**Comment by tazjin** [comment]
Thanks!

**Comment by superm1** [comment]
https://github.com/dell/thunderbolt-icm-dkms/commit/b11a8ad918a210249646ebfe170599c8f7c77c04
