### ISSUE TITLE
unknown type name uuid_be when dkms tries to compile

### ISSUE THREAD

**Issue by lx07** [dell/thunderbolt-icm-dkms#7]
**from make.log**

DKMS make.log for thunderbolt-dkms-r19.14d71aa for kernel 4.13.4-1-ARCH (x86_64)
Sun  8 Oct 22:43:52 CEST 2017
make: Entering directory '/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build'
make -C /lib/modules/4.13.4-1-ARCH/build M=`pwd` modules
make[1]: Entering directory '/usr/lib/modules/4.13.4-1-ARCH/build'
  CC [M]  /var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/nhi.o
In file included from /var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/ctl.h:13:0,
                 from /var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb.h:15,
                 from /var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/nhi.c:20:
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb_msgs.h:182:2: error: unknown type name ‘uuid_be’
  uuid_be ep_uuid;
  ^~~~~~~
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb_msgs.h:196:2: error: unknown type name ‘uuid_be’
  uuid_be ep_uuid;
  ^~~~~~~
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb_msgs.h:210:2: error: unknown type name ‘uuid_be’
  uuid_be ep_uuid;
  ^~~~~~~
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb_msgs.h:219:2: error: unknown type name ‘uuid_be’
  uuid_be ep_uuid;
  ^~~~~~~
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb_msgs.h:227:2: error: unknown type name ‘uuid_be’
  uuid_be ep_uuid;
  ^~~~~~~
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb_msgs.h:236:2: error: unknown type name ‘uuid_be’
  uuid_be ep_uuid;
  ^~~~~~~
In file included from /var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/nhi.c:20:0:
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb.h:104:2: error: unknown type name ‘uuid_be’
  uuid_be *uuid;
  ^~~~~~~
/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/tb.h:410:63: error: unknown type name ‘uuid_be’
 struct tb_switch *tb_switch_find_by_uuid(struct tb *tb, const uuid_be *uuid);
                                                               ^~~~~~~
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build/nhi.o] Error 1
make[1]: *** [Makefile:1512: _module_/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.13.4-1-ARCH/build'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/var/lib/dkms/thunderbolt-dkms/r19.14d71aa/build'

**Comment by superm1** [comment]
This module shouldn't be used in 4.13 and later anyway.  It's been merged in 4.13.
